name: no_01 policy wrapper

on:
  workflow_dispatch:
  push:
    branches:
      - no_01-attacker-*

permissions:
  contents: read

jobs:
  call-sensitive:
    uses: ./.github/workflows/no_01-policy-reusable-sensitive.yml
    secrets: inherit
